export interface PosInvoice {
    name: string
    owner: string
    creation: Date
    modified: Date
    modified_by: string
    docstatus: number
    idx: number
    title: string
    naming_series: string
    customer: string
    customer_name: string
    pos_profile: string
    consolidated_invoice: string
    is_pos: number
    is_return: number
    update_billed_amount_in_sales_order: number
    update_billed_amount_in_delivery_note: number
    company: string
    posting_date: Date
    posting_time: string
    set_posting_time: number
    due_date: Date
    currency: string
    conversion_rate: number
    selling_price_list: string
    price_list_currency: string
    plc_conversion_rate: number
    ignore_pricing_rule: number
    set_warehouse: string
    update_stock: number
    last_scanned_warehouse: null
    total_billing_amount: number
    total_qty: number
    base_total: number
    base_net_total: number
    total: number
    net_total: number
    total_net_weight: number
    taxes_and_charges: string
    tax_category: string
    base_total_taxes_and_charges: number
    total_taxes_and_charges: number
    loyalty_points: number
    loyalty_amount: number
    redeem_loyalty_points: number
    apply_discount_on: string
    base_discount_amount: number
    additional_discount_percentage: number
    discount_amount: number
    base_grand_total: number
    base_rounding_adjustment: number
    base_rounded_total: number
    base_in_words: string
    grand_total: number
    rounding_adjustment: number
    rounded_total: number
    in_words: string
    total_advance: number
    outstanding_amount: number
    allocate_advances_automatically: number
    base_paid_amount: number
    paid_amount: number
    base_change_amount: number
    change_amount: number
    account_for_change_amount: string
    write_off_amount: number
    base_write_off_amount: number
    write_off_outstanding_amount_automatically: number
    write_off_account: string
    write_off_cost_center: string
    letter_head: string
    group_same_items: number
    language: string
    is_discounted: number
    status: string
    debit_to: string
    party_account_currency: string
    is_opening: string
    remarks: string
    amount_eligible_for_commission: number
    commission_rate: number
    total_commission: number
    doctype: string
    items: Item[]
    payment_schedule: any[]
    payments: Payment[]
    timesheets: any[]
    taxes: any[]
    packed_items: any[]
    advances: any[]
    sales_team: any[]
    pricing_rules: any[]
}

export interface Item {
    name: string
    owner: string
    creation: Date
    modified: Date
    modified_by: string
    docstatus: number
    idx: number
    has_item_scanned: number
    item_code: string
    item_name: string
    description: string
    item_group: string
    image: string
    qty: number
    stock_uom: string
    uom: string
    conversion_factor: number
    stock_qty: number
    price_list_rate: number
    base_price_list_rate: number
    margin_type: string
    margin_rate_or_amount: number
    rate_with_margin: number
    discount_percentage: number
    discount_amount: number
    distributed_discount_amount: number
    base_rate_with_margin: number
    rate: number
    amount: number
    base_rate: number
    base_amount: number
    pricing_rules: string
    is_free_item: number
    grant_commission: number
    net_rate: number
    net_amount: number
    base_net_rate: number
    base_net_amount: number
    delivered_by_supplier: number
    income_account: string
    is_fixed_asset: number
    expense_account: string
    enable_deferred_revenue: number
    weight_per_unit: number
    total_weight: number
    warehouse: string
    use_serial_batch_fields: number
    allow_zero_valuation_rate: number
    item_tax_rate: string
    actual_batch_qty: number
    actual_qty: number
    batch_no: string
    delivered_qty: number
    cost_center: string
    page_break: number
    parent: string
    parentfield: string
    parenttype: string
    doctype: string
}

export interface Payment {
    name: string
    owner: string
    creation: Date
    modified: Date
    modified_by: string
    docstatus: number
    idx: number
    default: number
    mode_of_payment: string
    amount: number
    account: string
    type: string
    base_amount: number
    parent: string
    parentfield: string
    parenttype: string
    doctype: string
}
